#!/bin/bash


mkcd () {
  mkdir -p "$1"
  cd "$1"

cat <<EOF > main.c
/* $1 */
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

#include "$1.h"

int main (int argc, char *argv[], char *envp[]) {


return EXIT_SUCCESS;
}

EOF

cat <<EOF > $1.c
/* $1 */
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

#include "$1.h"



EOF

cat <<EOF > $1.h
#ifndef HEADER_$1
#define HEADER_$1


#endif
EOF


cat <<EOF > Makefile
all:
	gcc main.c $1.c -o start.elf

EOF


}

mkcd $1