#!/bin/bash


mkcd () {
cat <<EOF > $1.c
/* $1 */
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>

#include "$1.h"


EOF

cat <<EOF > $1.h
#ifndef HEADER_$1
#define HEADER_$1


#endif
EOF
}

mkcd $1