#!/bin/bash


mkcd () {
#  mkdir -p "$1"
#  cd "$1"

cat <<EOF > $1.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <!-- Copyright (C) 2014 RottinRob <rottinrob@gmail.com> -->  
  <link rel="author" title="RottinRob" href="mailto: (author) rottinrob@gmail.com" />
    <title>$1</title>
  <link href="greg.css" rel="stylesheet" type="text/css" />
  <script type="text/javascript">
  
  </script>
</head>
  <body>
    <h1></h1>
    
  </body>
</html>
EOF

#chmod +x $1.sh

}

mkcd $1